language: node_js

node_js:
  - "12"

branches:
  only:
    - master

cache:
  npm: true

script:
  - echo "skipping tests"
  - npm install -g vsce
  - vsce package
  - echo $TOKEN
  - vsce publish -p $TOKEN
