language: node_js

node_js:
  - "12"

branches:
  only:
    - master

cache:
  npm: true

script:
  - echo "skipping tests"

before_publish:
  - npm install -g vsce

publish:
  - vsce package
  - vsce publish -p $TOKEN
